### ISSUE TITLE
Linie 287 i sql script fejlede! VIEW: v_view_users

### ISSUE THREAD

**Issue by FredMar** [kimsand123/DBopgaveEksamen#1]
Måtte udkommentere:

/*
Delimiter //
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `nybaad_dk`@`%` 
    SQL SECURITY DEFINER
VIEW `v_view_users` AS
    SELECT 
        `operatoer`.`opr_id` AS `opr_id`,
        `operatoer`.`opr_navn` AS `opr_navn`,
        `operatoer`.`ini` AS `opr_ini`,
        `operatoer`.`cpr` AS `opr_cpr`
    FROM
        `operatoer`
    ORDER BY `operatoer`.`opr_id`
// Delimiter ;
*/

**Comment by hjaltebaekgaard** [comment]
Den er formentlig fra før navn blev splittet op i for- og efternavn.
